package update

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// EnvNoAutoUpdate turns the automatic update check off entirely.
const EnvNoAutoUpdate = "LK_NO_AUTO_UPDATE"

const (
	// caskName is the cask this binary is published as, and the one the upgrade
	// command names. Only a binary living under <prefix>/Caskroom/<caskName>/
	// may authorise `brew upgrade --cask lk`.
	caskName = "lk"

	// caskTap is the tap the published cask comes from, as Homebrew records it
	// (it strips the "homebrew-" prefix from linkanalabs/homebrew-tap).
	caskTap = "linkanalabs/tap"
)

// Method is how this binary got onto the machine.
type Method string

const (
	// MethodHomebrewCask is the published distribution: a cask in the
	// linkanalabs/homebrew-tap, generated by GoReleaser.
	MethodHomebrewCask Method = "homebrew_cask"
	// MethodOther covers scripts/install.sh, go install, and manual copies.
	MethodOther Method = "other"
)

// Install describes the current installation.
type Install struct {
	Method Method

	// resolved is the executable with symlinks followed. It is kept only to
	// locate Homebrew's metadata later; nothing outside this package needs it.
	resolved string
}

// Homebrew returns whether brew manages this installation, and therefore
// whether brew is the only thing allowed to replace the binary.
//
// Only a cask counts. lk ships as a cask, and the upgrade this package runs is
// `brew upgrade --cask lk`, which cannot act on a formula — so treating a Cellar
// path as upgradable would run a command guaranteed to fail. Should lk ever ship
// as a formula, that is a deliberate change and brings its own command.
func (i *Install) Homebrew() bool {
	return i.Method == MethodHomebrewCask
}

// Seams for tests: the real values depend on where the test binary happens to
// live, which is never a Homebrew path.
var (
	osExecutable = os.Executable
	evalSymlinks = filepath.EvalSymlinks
	readFile     = os.ReadFile
)

// Detect inspects the running binary's path. It costs no network, no child
// process and no file read — it runs on every lk invocation, so it stays down
// to path arithmetic. Reading Homebrew's receipt is deferred to CaskPath.
//
// This deliberately differs from gh and flyctl, which shell out to
// `brew --prefix` and test for a <prefix>/bin/ prefix. That approach breaks on
// Linux: os.Executable resolves symlinks there (via /proc/self/exe) but not on
// macOS, so on Linux the result is already the Cellar path, which never carries
// the /bin/ prefix. Matching Homebrew's own Caskroom layout after resolving
// symlinks works on both, and skips the ~25ms process spawn.
func Detect() (*Install, error) {
	exe, err := osExecutable()
	if err != nil {
		return nil, fmt.Errorf("locating the running binary: %w", err)
	}
	// A dangling or unreadable link must not sink detection — the unresolved
	// path is still informative.
	resolved := exe
	if r, err := evalSymlinks(exe); err == nil {
		resolved = r
	}

	// The full layout has to match, not merely contain a "Caskroom" element: a
	// binary someone copied into any directory of that name must not be able to
	// authorise brew replacing something.
	in := &Install{Method: MethodOther, resolved: resolved}
	if filepath.Base(caskDir(resolved)) == caskName {
		in.Method = MethodHomebrewCask
	}
	return in, nil
}

// installReceipt is the subset of Homebrew's INSTALL_RECEIPT.json we read.
// Homebrew writes this file itself, which is what makes it evidence rather than
// a guess: it names the tap the cask was installed from.
type installReceipt struct {
	Source struct {
		Tap  string `json:"tap"`
		Path string `json:"path"`
	} `json:"source"`
}

// CaskPath returns the local cask file this install came from, as recorded by
// Homebrew, and "" unless the receipt confirms brew installed this from our tap.
//
// The path layout alone is not evidence — any directory can be named Caskroom —
// so the receipt is what authorises brew to replace this binary: callers treat
// "" as "not confirmed" and refuse to self-upgrade. Verifying it this way costs
// nothing on the common path, because the read happens only after the daily
// budget has been claimed; shelling out to `brew --prefix` instead, as gh and
// flyctl do, would spawn a process on every single invocation and still get the
// Linux case wrong (see Detect).
func (i *Install) CaskPath() string {
	if i.Method != MethodHomebrewCask {
		return ""
	}
	dir := caskDir(i.resolved)
	if dir == "" {
		return ""
	}
	data, err := readFile(filepath.Join(dir, ".metadata", "INSTALL_RECEIPT.json"))
	if err != nil {
		return ""
	}
	var r installReceipt
	if err := json.Unmarshal(data, &r); err != nil {
		return ""
	}
	if r.Source.Tap != caskTap {
		return ""
	}
	return r.Source.Path
}

// caskDir walks up from <prefix>/Caskroom/<name>/<version>/<binary> to
// <prefix>/Caskroom/<name>, where the .metadata directory lives. It returns ""
// when no ancestor is a Caskroom, which is what makes the layout — rather than
// the mere presence of the word — decide.
func caskDir(resolved string) string {
	for dir := filepath.Dir(resolved); ; {
		parent := filepath.Dir(dir)
		if parent == dir {
			return "" // filesystem root, no Caskroom above
		}
		if filepath.Base(parent) == "Caskroom" {
			return dir
		}
		dir = parent
	}
}
