package update

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EnvNoAutoUpdate turns the automatic update check off entirely.
const EnvNoAutoUpdate = "LK_NO_AUTO_UPDATE"

// Method is how this binary got onto the machine.
type Method string

const (
	// MethodHomebrewCask is the published distribution: a cask in the
	// linkanalabs/homebrew-tap, generated by GoReleaser.
	MethodHomebrewCask Method = "homebrew_cask"
	// MethodOther covers scripts/install.sh, go install, and manual copies.
	MethodOther Method = "other"
)

// Install describes the current installation.
type Install struct {
	Method Method

	// resolved is the executable with symlinks followed. It is kept only to
	// locate Homebrew's metadata later; nothing outside this package needs it.
	resolved string
}

// Homebrew returns whether brew manages this installation, and therefore
// whether brew is the only thing allowed to replace the binary.
//
// Only a cask counts. lk ships as a cask, and the upgrade this package runs is
// `brew upgrade --cask lk`, which cannot act on a formula — so treating a Cellar
// path as upgradable would run a command guaranteed to fail. Should lk ever ship
// as a formula, that is a deliberate change and brings its own command.
func (i *Install) Homebrew() bool {
	return i.Method == MethodHomebrewCask
}

// Seams for tests: the real values depend on where the test binary happens to
// live, which is never a Homebrew path.
var (
	osExecutable = os.Executable
	evalSymlinks = filepath.EvalSymlinks
	readFile     = os.ReadFile
)

// Detect inspects the running binary's path. It costs no network, no child
// process and no file read — it runs on every lk invocation, so it stays down
// to path arithmetic. Reading Homebrew's receipt is deferred to CaskPath.
//
// This deliberately differs from gh and flyctl, which shell out to
// `brew --prefix` and test for a <prefix>/bin/ prefix. That approach breaks on
// Linux: os.Executable resolves symlinks there (via /proc/self/exe) but not on
// macOS, so on Linux the result is already the Cellar path, which never carries
// the /bin/ prefix. Matching the Caskroom path segment after resolving symlinks
// works on both, and skips the ~25ms process spawn.
func Detect() (*Install, error) {
	exe, err := osExecutable()
	if err != nil {
		return nil, fmt.Errorf("locating the running binary: %w", err)
	}
	// A dangling or unreadable link must not sink detection — the unresolved
	// path is still informative.
	resolved := exe
	if r, err := evalSymlinks(exe); err == nil {
		resolved = r
	}

	in := &Install{Method: MethodOther, resolved: resolved}
	if hasSegment(resolved, "Caskroom") {
		in.Method = MethodHomebrewCask
	}
	return in, nil
}

// installReceipt is the subset of Homebrew's INSTALL_RECEIPT.json we read.
type installReceipt struct {
	Source struct {
		Path string `json:"path"`
	} `json:"source"`
}

// CaskPath returns the local cask file this install came from, as recorded by
// Homebrew. That file is what tells us whether brew's metadata is fresh enough
// for `brew upgrade` to do anything.
//
// It reads the disk, so it is called only once a decision actually needs it —
// never on the common path of an ordinary command. An absent or unreadable
// receipt yields "", which callers treat as "cannot tell".
func (i *Install) CaskPath() string {
	if i.Method != MethodHomebrewCask {
		return ""
	}
	dir := caskDir(i.resolved)
	if dir == "" {
		return ""
	}
	data, err := readFile(filepath.Join(dir, ".metadata", "INSTALL_RECEIPT.json"))
	if err != nil {
		return ""
	}
	var r installReceipt
	if err := json.Unmarshal(data, &r); err != nil {
		return ""
	}
	return r.Source.Path
}

// caskDir walks up from <prefix>/Caskroom/<name>/<version>/<binary> to
// <prefix>/Caskroom/<name>, where the .metadata directory lives.
func caskDir(resolved string) string {
	for dir := filepath.Dir(resolved); ; {
		parent := filepath.Dir(dir)
		if parent == dir {
			return "" // filesystem root, no Caskroom above
		}
		if filepath.Base(parent) == "Caskroom" {
			return dir
		}
		dir = parent
	}
}

// hasSegment reports whether want appears as a whole path element, so a user
// directory that merely contains the word is not mistaken for a Homebrew one.
func hasSegment(path, want string) bool {
	for _, seg := range strings.Split(filepath.ToSlash(path), "/") {
		if seg == want {
			return true
		}
	}
	return false
}
