package update

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// realCask is the shape GoReleaser actually commits to the tap.
const realCask = `# This file was generated by GoReleaser. DO NOT EDIT.
cask "lk" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "22692f93c37033d8b9b5bf08611a6763ce6ec6718dee02f6a52d80479fadd296"
      url "https://github.com/linkanalabs/cli/releases/download/v#{version}/lk_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "lk"
  homepage "https://github.com/linkanalabs/cli"
end
`

func stubTapURL(t *testing.T, url string) {
	t.Helper()
	prev := tapCaskURL
	tapCaskURL = url
	t.Cleanup(func() { tapCaskURL = prev })
}

func stubReleasesURL(t *testing.T, url string) {
	t.Helper()
	prev := releasesLatestURL
	releasesLatestURL = url
	t.Cleanup(func() { releasesLatestURL = prev })
}

func TestParseCaskVersion(t *testing.T) {
	cases := []struct {
		name string
		body string
		want string
	}{
		{"real cask", realCask, "0.8.1"},
		{"no indentation", "cask \"lk\" do\nversion \"1.0.0\"\n", "1.0.0"},
		{"prerelease", "  version \"1.0.0-rc.1\"\n", "1.0.0-rc.1"},
		{"first match wins", "  version \"1.0.0\"\n  version \"2.0.0\"\n", "1.0.0"},
		{"no version stanza", "cask \"lk\" do\nend\n", ""},
		{"version mentioned but not a stanza", "  url \"...v#{version}...\"\n", ""},
		{"empty", "", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := parseCaskVersion([]byte(c.body)); got != c.want {
				t.Errorf("parseCaskVersion() = %q, want %q", got, c.want)
			}
		})
	}
}

func TestTapRemote(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(realCask))
	}))
	defer srv.Close()
	stubTapURL(t, srv.URL)

	got, err := TapRemote(context.Background(), srv.Client())
	if err != nil {
		t.Fatalf("TapRemote() error = %v", err)
	}
	if got != "0.8.1" {
		t.Errorf("TapRemote() = %q, want 0.8.1", got)
	}
}

// The tap request must never carry an Authorization header: this package is
// the one place lk talks to a host that is not the Linkana backend.
func TestTapRemoteSendsNoCredentials(t *testing.T) {
	var gotAuth string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotAuth = r.Header.Get("Authorization")
		_, _ = w.Write([]byte(realCask))
	}))
	defer srv.Close()
	stubTapURL(t, srv.URL)

	if _, err := TapRemote(context.Background(), srv.Client()); err != nil {
		t.Fatalf("TapRemote() error = %v", err)
	}
	if gotAuth != "" {
		t.Errorf("Authorization header leaked to the tap host: %q", gotAuth)
	}
}

func TestTapRemoteErrors(t *testing.T) {
	t.Run("not found", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.WriteHeader(http.StatusNotFound)
		}))
		defer srv.Close()
		stubTapURL(t, srv.URL)

		if _, err := TapRemote(context.Background(), srv.Client()); err == nil {
			t.Fatal("expected an error on 404")
		}
	})

	t.Run("no version stanza", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			_, _ = w.Write([]byte("cask \"lk\" do\nend\n"))
		}))
		defer srv.Close()
		stubTapURL(t, srv.URL)

		if _, err := TapRemote(context.Background(), srv.Client()); err == nil {
			t.Fatal("expected an error when the cask carries no version")
		}
	})

	t.Run("unreachable", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(http.ResponseWriter, *http.Request) {}))
		url := srv.URL
		srv.Close() // nothing is listening now
		stubTapURL(t, url)

		if _, err := TapRemote(context.Background(), http.DefaultClient); err == nil {
			t.Fatal("expected an error when the host is unreachable")
		}
	})
}

func TestTapLocal(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "lk.rb")
	if err := os.WriteFile(path, []byte(realCask), 0o644); err != nil {
		t.Fatal(err)
	}

	got, err := TapLocal(path)
	if err != nil {
		t.Fatalf("TapLocal() error = %v", err)
	}
	if got != "0.8.1" {
		t.Errorf("TapLocal() = %q, want 0.8.1", got)
	}
}

func TestTapLocalErrors(t *testing.T) {
	t.Run("empty path", func(t *testing.T) {
		if _, err := TapLocal(""); err == nil {
			t.Fatal("expected an error for an empty cask path")
		}
	})
	t.Run("missing file", func(t *testing.T) {
		if _, err := TapLocal(filepath.Join(t.TempDir(), "absent.rb")); err == nil {
			t.Fatal("expected an error for a missing cask file")
		}
	})
	t.Run("no version stanza", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "lk.rb")
		if err := os.WriteFile(path, []byte("cask \"lk\" do\nend\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := TapLocal(path); err == nil {
			t.Fatal("expected an error when the cask carries no version")
		}
	})
}

// Release reads the tag out of the redirect rather than calling the REST API,
// which is capped at 60 requests/hour per IP.
func TestRelease(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Location", "https://github.com/linkanalabs/cli/releases/tag/v0.8.1")
		w.WriteHeader(http.StatusFound)
	}))
	defer srv.Close()
	stubReleasesURL(t, srv.URL)

	got, err := Release(context.Background(), srv.Client())
	if err != nil {
		t.Fatalf("Release() error = %v", err)
	}
	if got != "v0.8.1" {
		t.Errorf("Release() = %q, want v0.8.1", got)
	}
}

// The redirect must not be followed: following it would fetch a full HTML page
// for no reason, and the tag is already in the header.
func TestReleaseDoesNotFollowRedirect(t *testing.T) {
	var hits int
	mux := http.NewServeMux()
	mux.HandleFunc("/releases/latest", func(w http.ResponseWriter, _ *http.Request) {
		hits++
		w.Header().Set("Location", "/releases/tag/v1.2.3")
		w.WriteHeader(http.StatusFound)
	})
	mux.HandleFunc("/releases/tag/", func(w http.ResponseWriter, _ *http.Request) {
		hits++
		_, _ = w.Write([]byte("<html>should not be fetched</html>"))
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()
	stubReleasesURL(t, srv.URL+"/releases/latest")

	got, err := Release(context.Background(), srv.Client())
	if err != nil {
		t.Fatalf("Release() error = %v", err)
	}
	if got != "v1.2.3" {
		t.Errorf("Release() = %q, want v1.2.3", got)
	}
	if hits != 1 {
		t.Errorf("made %d requests, want exactly 1 (redirect was followed)", hits)
	}
}

// Setting CheckRedirect must not mutate the caller's client: doctor reuses one
// client for the backend reachability probe too.
func TestReleaseLeavesCallerClientAlone(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Location", "/releases/tag/v1.0.0")
		w.WriteHeader(http.StatusFound)
	}))
	defer srv.Close()
	stubReleasesURL(t, srv.URL)

	hc := srv.Client()
	if _, err := Release(context.Background(), hc); err != nil {
		t.Fatalf("Release() error = %v", err)
	}
	if hc.CheckRedirect != nil {
		t.Error("Release mutated the caller's http.Client")
	}
}

func TestReleaseErrors(t *testing.T) {
	t.Run("no location header", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.WriteHeader(http.StatusOK)
		}))
		defer srv.Close()
		stubReleasesURL(t, srv.URL)

		if _, err := Release(context.Background(), srv.Client()); err == nil {
			t.Fatal("expected an error when there is no redirect to read")
		}
	})

	t.Run("location without a tag", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Location", "https://github.com/linkanalabs/cli/releases")
			w.WriteHeader(http.StatusFound)
		}))
		defer srv.Close()
		stubReleasesURL(t, srv.URL)

		if _, err := Release(context.Background(), srv.Client()); err == nil {
			t.Fatal("expected an error when the redirect carries no tag")
		}
	})

	t.Run("unreachable", func(t *testing.T) {
		srv := httptest.NewServer(http.HandlerFunc(func(http.ResponseWriter, *http.Request) {}))
		url := srv.URL
		srv.Close()
		stubReleasesURL(t, url)

		if _, err := Release(context.Background(), http.DefaultClient); err == nil {
			t.Fatal("expected an error when the host is unreachable")
		}
	})
}

// A hostile or broken tap must not be able to make lk read an unbounded body.
func TestTapRemoteBodyIsBounded(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(strings.Repeat("x", maxBodyBytes+1024)))
	}))
	defer srv.Close()
	stubTapURL(t, srv.URL)

	// No version in that payload, so this must fail rather than hang or
	// allocate without bound.
	if _, err := TapRemote(context.Background(), srv.Client()); err == nil {
		t.Fatal("expected an error for a body with no version stanza")
	}
}
